import React, { forwardRef } from 'react';
import type { ClientSong } from '@/lib/types';
import { Music2, ArrowUp, ArrowDown, Minus } from 'lucide-react';
import { Badge } from './ui/badge';
import Image from 'next/image';

interface ChartImageProps {
  chartTitle: string;
  tracks: ClientSong[];
  startDate: Date;
  endDate: Date;
}

export const ChartImage = forwardRef<HTMLDivElement, ChartImageProps>(({ chartTitle, tracks, startDate, endDate }, ref) => {
    
    // We must use inline styles for html-to-image to capture them correctly.
    // We also must use absolute URLs for images.

    const formattedDate = `${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()}`;

    return (
        <div 
            ref={ref}
            style={{
                width: '800px',
                height: '800px',
                display: 'flex',
                flexDirection: 'column',
                fontFamily: '"Poppins", sans-serif',
                color: 'white',
                background: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)', // Dark indigo gradient
                padding: '40px',
            }}
        >
            <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                <Music2 style={{ width: '40px', height: '40px', color: '#a78bfa' }} />
                <div>
                    <h1 style={{ fontSize: '36px', fontWeight: 'bold' }}>{chartTitle}</h1>
                    <p style={{ fontSize: '16px', color: '#e5e7eb', marginTop: '-4px' }}>{formattedDate}</p>
                </div>
            </div>
            
            <div style={{ marginTop: '20px', display: 'flex', flexDirection: 'column', gap: '2px' }}>
                {tracks.map((track, index) => {
                    let rankChange;
                    if (track.change === "new") {
                        rankChange = <Badge variant="secondary" className="bg-violet-400 text-violet-900">NEW</Badge>;
                    } else if (track.change === "up") {
                        rankChange = <ArrowUp style={{ width: '20px', height: '20px', color: '#4ade80' }} />;
                    } else if (track.change === "down") {
                        rankChange = <ArrowDown style={{ width: '20px', height: '20px', color: '#f87171' }} />;
                    } else {
                        rankChange = <Minus style={{ width: '20px', height: '20px', color: '#9ca3af' }} />;
                    }
                    
                    return (
                        <div 
                            key={track.rank}
                            style={{
                                display: 'flex',
                                alignItems: 'center',
                                gap: '12px',
                                background: 'rgba(255, 255, 255, 0.05)',
                                borderRadius: '8px',
                                padding: '4px',
                            }}
                        >
                            <div style={{ fontSize: '20px', fontWeight: 'bold', width: '40px', textAlign: 'center', color: '#d1d5db' }}>
                                {track.rank}
                            </div>
                            <img
                                src={track.albumArtUrl}
                                alt={`Album art for ${track.title}`}
                                crossOrigin="anonymous"
                                style={{
                                    width: '48px',
                                    height: '48px',
                                    borderRadius: '4px',
                                    objectFit: 'cover',
                                }}
                            />
                            <div style={{ flexGrow: 1, minWidth: 0 }}>
                                <p style={{ fontSize: '16px', fontWeight: '600', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{track.title}</p>
                                <p style={{ fontSize: '13px', color: '#e5e7eb', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{track.artist}</p>
                            </div>
                             <div style={{ width: '40px', display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
                                {rankChange}
                            </div>
                        </div>
                    );
                })}
            </div>
            <div style={{ flexGrow: 1 }}></div>
            <div style={{ textAlign: 'right', fontSize: '16px', color: '#94a3b8' }}>
                Generated by DreamCharts
            </div>
        </div>
    );
});

ChartImage.displayName = 'ChartImage';
